#!/usr/bin/env bash

# RO:WHAT — Runs the FINAL_BETA Phase 1 desktop baseline inventory and
#           records the clean-user manual journey.
# RO:WHY — Phase 1 must capture existing product truth before redesign.
# RO:INTERACTS — onboarding acceptance, tab hit-testing checker, desktop
#                React source, FINAL_BETA Phase 1 audit records.
# RO:INVARIANTS — no secret capture; no runtime source mutation; no fake green;
#                 destructive reset is manual and disposable-profile only.
# RO:METRICS — prints deterministic GREEN/RED/RECORDED markers.
# RO:CONFIG — mode: inventory, automated, manual, status, help.
# RO:SECURITY — never record PINs, recovery words, keys, or raw capabilities.
# RO:TEST — bash -n and focused Phase 1A verification.

set -uo pipefail

SCRIPT_DIR="$(
  cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 &&
    pwd
)"

ROOT="$(
  cd "$SCRIPT_DIR/../../.." >/dev/null 2>&1 &&
    pwd
)"

APP_ROOT="$ROOT/apps/crablink-tauri"
AUDIT_DOC="$ROOT/docs/tauri/FINAL_BETA_PHASE1_CLEAN_BASELINE_AUDIT.md"
SOURCE_REPORT="$ROOT/docs/tauri/FINAL_BETA_PHASE1_SOURCE_INVENTORY.txt"
MANUAL_RESULTS="$ROOT/docs/tauri/FINAL_BETA_PHASE1_MANUAL_RESULTS.md"

TAB_CHECKER="$ROOT/scripts/check-crablink-tab-hit-testing-boundary.mjs"
ONBOARDING_AUTOMATED="$APP_ROOT/scripts/onboarding_phase11a_desktop_automated_acceptance.sh"

MODE="${1:-status}"

require_command() {
  local command_name="$1"

  if command -v "$command_name" >/dev/null 2>&1; then
    return 0
  fi

  printf 'MISSING_COMMAND=%s\n' "$command_name"
  return 1
}

require_file() {
  local label="$1"
  local file_path="$2"

  if [ -f "$file_path" ]; then
    printf '%s=PRESENT\n' "$label"
    return 0
  fi

  printf '%s=MISSING:%s\n' "$label" "$file_path"
  return 1
}

print_header() {
  printf '%s\n' \
    "FINAL_BETA_PHASE1_ACCEPTANCE=STARTED" \
    "MODE=$MODE" \
    "ACTIVE_PHASE=FINAL_BETA_PHASE1_CLEAN_DESKTOP_BASELINE" \
    "DESIGN_SYSTEM_PHASE=FINAL_BETA_PHASE2" \
    "RUNTIME_SOURCE_MUTATION=NO" \
    "RUSTYONIONS_MUTATION=NO" \
    "MOBILE_RUNTIME_MUTATION=NO"
}

write_scan_section() {
  local report_file="$1"
  local label="$2"
  local pattern="$3"
  local matches_file="${report_file}.${label}.matches.$$"
  local match_count=0

  if rg \
    --line-number \
    --ignore-case \
    --glob '*.js' \
    --glob '*.jsx' \
    --glob '*.ts' \
    --glob '*.tsx' \
    --glob '*.css' \
    "$pattern" \
    "$APP_ROOT/src" > "$matches_file" 2>/dev/null
  then
    match_count="$(
      wc -l < "$matches_file" |
        tr -d '[:space:]'
    )"
  else
    match_count=0
    : > "$matches_file"
  fi

  {
    printf '\n=== %s ===\n' "$label"
    printf '%s_MATCH_COUNT=%s\n' "$label" "$match_count"
    cat "$matches_file"
  } >> "$report_file"

  rm -f "$matches_file"

  printf '%s_MATCH_COUNT=%s\n' "$label" "$match_count"
}

run_inventory() {
  local failures=0
  local report_tmp="${SOURCE_REPORT}.tmp.$$"

  print_header

  require_command rg || failures=$((failures + 1))
  require_command node || failures=$((failures + 1))

  require_file \
    "PHASE1_AUDIT_DOCUMENT" \
    "$AUDIT_DOC" || failures=$((failures + 1))

  for required_source in \
    "$APP_ROOT/src/pages/home/HomePage.jsx" \
    "$APP_ROOT/src/pages/profile/ProfilePublicView.jsx" \
    "$APP_ROOT/src/pages/site/SiteGuidedSetup.jsx" \
    "$APP_ROOT/src/app/shell/Shell.jsx" \
    "$APP_ROOT/src/app/shell/TopBar.jsx" \
    "$APP_ROOT/src/app/routeRegistry.js"
  do
    require_file \
      "SOURCE_$(basename "$required_source" | tr '.-' '__')" \
      "$required_source" || failures=$((failures + 1))
  done

  if [ "$failures" -ne 0 ]; then
    printf '%s\n' \
      "FINAL_BETA_PHASE1_SOURCE_INVENTORY=RED" \
      "FAILURE_COUNT=$failures" \
      "NEXT_ACTION=FIX_FIRST_REPORTED_FAILURE"

    return 1
  fi

  {
    printf '%s\n' \
      "FINAL_BETA Phase 1 Source/UI Inventory" \
      "Generated by final_beta_phase1_clean_desktop_acceptance.sh" \
      "This is a diagnostic inventory, not an automatic removal list." \
      "" \
      "RUNTIME_SOURCE_MUTATION=NO" \
      "RUSTYONIONS_MUTATION=NO" \
      "MOBILE_RUNTIME_MUTATION=NO"
  } > "$report_tmp"

  write_scan_section \
    "$report_tmp" \
    "RAW_JSON_OR_PREFORMATTED_DATA" \
    'JSON\.stringify|<pre\b|raw[[:space:]]+json|manifest[[:space:]]+json|proof[[:space:]]+json'

  write_scan_section \
    "$report_tmp" \
    "DEVELOPER_TEST_WORDING" \
    '\bdeveloper\b|\bdebug\b|\btest(ing)?\b|\bsmoke\b|\bfixture\b|\bproof\b|\bmigration\b'

  write_scan_section \
    "$report_tmp" \
    "FAKE_OR_FALLBACK_WORDING" \
    '\bmock\b|\bfake\b|\bfallback\b|\bplaceholder\b|\bsample\b|\bdemo\b|\bstub\b'

  write_scan_section \
    "$report_tmp" \
    "INLINE_STYLE_SURFACES" \
    'style=\{\{'

  write_scan_section \
    "$report_tmp" \
    "BUTTON_STYLE_SURFACES" \
    '\.button\b|\.btn\b|button[[:space:]]*\{|button:|button\.'

  {
    printf '\n=== KNOWN_BASELINE_MARKERS ===\n'

    for marker in \
      "Route Smoke Dashboard" \
      "Manual smoke sequence" \
      "Local proof memory, not backend authority"
    do
      if rg -Fq \
        "$marker" \
        "$APP_ROOT/src/pages/home/HomePage.jsx"
      then
        printf 'HOME_MARKER=%s:PRESENT\n' "$marker"
      else
        printf 'HOME_MARKER=%s:ABSENT\n' "$marker"
      fi
    done

    if rg -Fq \
      "This page is read-only" \
      "$APP_ROOT/src/pages/profile/ProfilePublicView.jsx"
    then
      printf '%s\n' "PUBLIC_PROFILE_READ_ONLY=PRESENT"
    else
      printf '%s\n' "PUBLIC_PROFILE_READ_ONLY=NOT_CONFIRMED"
    fi

    if rg -Fq \
      "Import HTML" \
      "$APP_ROOT/src/pages/site/SiteGuidedSetup.jsx"
    then
      printf '%s\n' "NORMAL_SITE_HTML_IMPORT=PRESENT"
    else
      printf '%s\n' "NORMAL_SITE_HTML_IMPORT=ABSENT"
    fi

    if rg -Fq \
      'label="Root HTML"' \
      "$APP_ROOT/src/pages/site/SiteGuidedSetup.jsx"
    then
      printf '%s\n' "NORMAL_SITE_ROOT_HTML_EDITOR=PRESENT"
    else
      printf '%s\n' "NORMAL_SITE_ROOT_HTML_EDITOR=ABSENT"
    fi
  } >> "$report_tmp"

  mv "$report_tmp" "$SOURCE_REPORT" || {
    rm -f "$report_tmp"

    printf '%s\n' \
      "FINAL_BETA_PHASE1_SOURCE_INVENTORY=RED" \
      "FAILURE=SOURCE_REPORT_ATOMIC_WRITE_FAILED"

    return 1
  }

  printf '%s\n' \
    "FINAL_BETA_PHASE1_SOURCE_INVENTORY=RECORDED" \
    "SOURCE_REPORT=$SOURCE_REPORT" \
    "RUNTIME_SOURCE_MUTATION=NO" \
    "NEXT_ACTION=RUN_AUTOMATED_OR_MANUAL_MODE"

  return 0
}

run_automated() {
  local failures=0

  print_header

  run_inventory || failures=$((failures + 1))

  printf '\n=== TAB HIT-TESTING BOUNDARY ===\n'

  if node "$TAB_CHECKER"; then
    printf '%s\n' "TAB_HIT_TESTING_BOUNDARY=GREEN"
  else
    printf '%s\n' "TAB_HIT_TESTING_BOUNDARY=RED"
    failures=$((failures + 1))
  fi

  printf '\n=== EXISTING ONBOARDING AUTOMATED ACCEPTANCE ===\n'

  if bash "$ONBOARDING_AUTOMATED"; then
    printf '%s\n' "ONBOARDING_AUTOMATED_BASELINE=GREEN"
  else
    printf '%s\n' "ONBOARDING_AUTOMATED_BASELINE=RED"
    failures=$((failures + 1))
  fi

  printf '\n=== AUTOMATED RESULT ===\n'

  if [ "$failures" -eq 0 ]; then
    printf '%s\n' \
      "FINAL_BETA_PHASE1_AUTOMATED_BASELINE=GREEN" \
      "FAILURE_COUNT=0" \
      "MANUAL_JOURNEY_RECORDED=NO" \
      "PHASE1_CLOSED=NO" \
      "NEXT_ACTION=RUN_MANUAL_MODE"

    return 0
  fi

  printf '%s\n' \
    "FINAL_BETA_PHASE1_AUTOMATED_BASELINE=RED" \
    "FAILURE_COUNT=$failures" \
    "PHASE1_CLOSED=NO" \
    "NEXT_ACTION=FIX_FIRST_REPORTED_FAILURE"

  return 1
}

prompt_status() {
  local step_label="$1"
  local response=""

  while true; do
    printf '%s [GREEN/RED/SKIPPED]: ' "$step_label"
    IFS= read -r response || return 1

    case "$response" in
      GREEN|RED|SKIPPED)
        printf '%s' "$response"
        return 0
        ;;
      *)
        printf '%s\n' \
          "Enter exactly GREEN, RED, or SKIPPED." >&2
        ;;
    esac
  done
}

run_manual() {
  local confirmation=""
  local results_tmp="${MANUAL_RESULTS}.tmp.$$"
  local red_count=0
  local skipped_count=0
  local step=""
  local label=""
  local status=""
  local note=""

  local steps=(
    "CLEAN_FIRST_RUN|Clean first run has no stale identity or dev user"
    "APP_LAUNCH|Application launches and accepts pointer and keyboard input"
    "USERNAME_SELECTION|Username selection and availability flow are understandable"
    "PASSPORT_CREATE|Local Passport creation completes truthfully"
    "RECOVERY_CEREMONY|Native recovery ceremony completes without WebView phrase custody"
    "PIN_SETUP|Native PIN setup completes without React PIN custody"
    "PROFILE_SETUP|Profile setup saves or skips coherently"
    "HOME_HANDOFF|Onboarding completion reaches the intended Home route"
    "RESTART_UNLOCK|Restart and unlock behavior match policy"
    "OWN_PROFILE|Own profile opens without manual route reconstruction"
    "IMAGE_PUBLISH|One image publication path is recorded"
    "POST_OR_ARTICLE_PUBLISH|One post or article publication path is recorded"
    "SITE_CREATE|One site creation path is recorded"
    "PAID_ITEM_READ|One explicitly confirmed paid-item path is recorded"
    "RECEIPT_VIEW|Backend-derived receipt display is recorded"
    "CONFIRMED_ROC_VIEW|Backend-derived confirmed ROC display is recorded"
    "LOCK_UNLOCK|Explicit lock and subsequent unlock are recorded"
    "CLEAR_RESET|Disposable test profile clear/reset is recorded"
    "POINTER_INPUT|Buttons inputs scrolling and route controls respond reliably"
    "UI_PROBLEM_INVENTORY|Confusing labels dead ends raw JSON dev wording and style drift are recorded"
  )

  print_header

  printf '%s\n' \
    "" \
    "MANUAL ACCEPTANCE SAFETY" \
    "Use a disposable test profile." \
    "Do not enter PINs, recovery words, keys, capabilities, or secrets into notes." \
    "This runner records observations only." \
    "It does not clear app data or mutate Passport storage." \
    "" \
    "Launch the desktop app separately with:" \
    "cd $APP_ROOT" \
    "npm run tauri:dev:mac-media" \
    ""

  printf '%s' \
    "Type FINAL_BETA_PHASE1_DISPOSABLE_PROFILE to continue: "

  IFS= read -r confirmation || {
    printf '%s\n' \
      "FINAL_BETA_PHASE1_MANUAL_JOURNEY=RED" \
      "FAILURE=CONFIRMATION_INPUT_FAILED"
    return 1
  }

  if [ "$confirmation" != "FINAL_BETA_PHASE1_DISPOSABLE_PROFILE" ]; then
    printf '%s\n' \
      "FINAL_BETA_PHASE1_MANUAL_JOURNEY=NOT_RUN" \
      "FAILURE=DISPOSABLE_PROFILE_CONFIRMATION_MISSING"
    return 1
  fi

  {
    printf '%s\n' \
      "# FINAL_BETA Phase 1 Manual Results" \
      "" \
      "<!-- FINAL_BETA_PHASE1_MANUAL_RESULTS_V1 -->" \
      "" \
      "No PINs, recovery words, keys, capabilities, or private material" \
      "may be recorded in this file." \
      "" \
      "| Step | Status | Redacted observation |" \
      "|---|---|---|"
  } > "$results_tmp"

  for step in "${steps[@]}"; do
    label="${step%%|*}"
    step="${step#*|}"

    status="$(prompt_status "$step")" || {
      rm -f "$results_tmp"

      printf '%s\n' \
        "FINAL_BETA_PHASE1_MANUAL_JOURNEY=RED" \
        "FAILURE=STATUS_INPUT_FAILED"

      return 1
    }

    printf '%s' \
      "Redacted observation for $label (blank allowed): "

    IFS= read -r note || note=""

    note="$(
      printf '%s' "$note" |
        tr '\n\r|' '   '
    )"

    printf '| %s | %s | %s |\n' \
      "$label" \
      "$status" \
      "$note" >> "$results_tmp"

    case "$status" in
      RED)
        red_count=$((red_count + 1))
        ;;
      SKIPPED)
        skipped_count=$((skipped_count + 1))
        ;;
    esac
  done

  {
    printf '\n## Result\n\n'
    printf '```text\n'
    printf 'MANUAL_STEP_COUNT=%s\n' "${#steps[@]}"
    printf 'MANUAL_RED_COUNT=%s\n' "$red_count"
    printf 'MANUAL_SKIPPED_COUNT=%s\n' "$skipped_count"
    printf 'MANUAL_JOURNEY_RECORDED=YES\n'
    printf 'PHASE1_CLOSED=NO\n'

    if [ "$red_count" -eq 0 ] &&
       [ "$skipped_count" -eq 0 ]
    then
      printf 'NEXT_ACTION=REVIEW_UI_PROBLEM_INVENTORY_AND_CLOSE_PHASE1\n'
    else
      printf 'NEXT_ACTION=FIX_BLOCKERS_OR_RECORD_SKIPPED_JUSTIFICATION\n'
    fi

    printf '```\n'
  } >> "$results_tmp"

  mv "$results_tmp" "$MANUAL_RESULTS" || {
    rm -f "$results_tmp"

    printf '%s\n' \
      "FINAL_BETA_PHASE1_MANUAL_JOURNEY=RED" \
      "FAILURE=MANUAL_RESULTS_ATOMIC_WRITE_FAILED"

    return 1
  }

  printf '%s\n' \
    "FINAL_BETA_PHASE1_MANUAL_JOURNEY=RECORDED" \
    "MANUAL_RED_COUNT=$red_count" \
    "MANUAL_SKIPPED_COUNT=$skipped_count" \
    "MANUAL_RESULTS=$MANUAL_RESULTS" \
    "PHASE1_CLOSED=NO"

  if [ "$red_count" -eq 0 ] &&
     [ "$skipped_count" -eq 0 ]
  then
    printf '%s\n' \
      "CLEAN_FIRST_RUN=RECORDED" \
      "RESTART_UNLOCK=RECORDED" \
      "PROFILE_HANDOFF=RECORDED" \
      "CONTENT_PUBLISH_BASELINE=RECORDED" \
      "PAID_RECEIPT_BASELINE=RECORDED" \
      "UI_PROBLEM_INVENTORY=RECORDED" \
      "NEXT_ACTION=RUN_STATUS_AND_REVIEW_PHASE1_CLOSEOUT"

    return 0
  fi

  printf '%s\n' \
    "NEXT_ACTION=FIX_RECORDED_BLOCKERS_OR_COMPLETE_SKIPPED_STEPS"

  return 1
}

run_status() {
  local failures=0
  local manual_red_count=0
  local manual_skipped_count=0

  print_header

  require_file \
    "PHASE1_AUDIT_DOCUMENT" \
    "$AUDIT_DOC" || failures=$((failures + 1))

  if [ -f "$SOURCE_REPORT" ]; then
    printf '%s\n' "SOURCE_PROBLEM_INVENTORY=RECORDED"
  else
    printf '%s\n' "SOURCE_PROBLEM_INVENTORY=NOT_RECORDED"
  fi

  if [ -f "$MANUAL_RESULTS" ]; then
    printf '%s\n' "MANUAL_JOURNEY=RECORDED"

    manual_red_count="$(
      grep -Ec '\| RED \|' "$MANUAL_RESULTS" 2>/dev/null ||
        true
    )"

    manual_skipped_count="$(
      grep -Ec '\| SKIPPED \|' "$MANUAL_RESULTS" 2>/dev/null ||
        true
    )"

    printf '%s\n' \
      "MANUAL_RED_COUNT=$manual_red_count" \
      "MANUAL_SKIPPED_COUNT=$manual_skipped_count"
  else
    printf '%s\n' \
      "MANUAL_JOURNEY=NOT_RECORDED" \
      "MANUAL_RED_COUNT=0" \
      "MANUAL_SKIPPED_COUNT=0"
  fi

  if [ "$failures" -ne 0 ]; then
    printf '%s\n' \
      "FINAL_BETA_PHASE1_STATUS=RED" \
      "FAILURE_COUNT=$failures" \
      "NEXT_ACTION=FIX_FIRST_REPORTED_FAILURE"

    return 1
  fi

  if [ ! -f "$SOURCE_REPORT" ]; then
    printf '%s\n' \
      "FINAL_BETA_PHASE1_STATUS=OPEN" \
      "NEXT_ACTION=RUN_INVENTORY_MODE"

    return 0
  fi

  if [ ! -f "$MANUAL_RESULTS" ]; then
    printf '%s\n' \
      "FINAL_BETA_PHASE1_STATUS=OPEN" \
      "NEXT_ACTION=RUN_AUTOMATED_THEN_MANUAL_MODE"

    return 0
  fi

  if [ "$manual_red_count" -ne 0 ] ||
     [ "$manual_skipped_count" -ne 0 ]
  then
    printf '%s\n' \
      "FINAL_BETA_PHASE1_STATUS=BLOCKED" \
      "NEXT_ACTION=FIX_RECORDED_BLOCKERS_OR_COMPLETE_SKIPPED_STEPS"

    return 0
  fi

  printf '%s\n' \
    "FINAL_BETA_PHASE1_STATUS=READY_FOR_CLOSEOUT_REVIEW" \
    "CLEAN_FIRST_RUN=RECORDED" \
    "RESTART_UNLOCK=RECORDED" \
    "PROFILE_HANDOFF=RECORDED" \
    "CONTENT_PUBLISH_BASELINE=RECORDED" \
    "PAID_RECEIPT_BASELINE=RECORDED" \
    "UI_PROBLEM_INVENTORY=RECORDED" \
    "PHASE1_CLOSED=NO" \
    "NEXT_ACTION=REVIEW_RESULTS_BEFORE_PHASE1_GREEN"

  return 0
}

print_help() {
  cat <<'FINAL_BETA_PHASE1_HELP'
Usage:

  final_beta_phase1_clean_desktop_acceptance.sh status
  final_beta_phase1_clean_desktop_acceptance.sh inventory
  final_beta_phase1_clean_desktop_acceptance.sh automated
  final_beta_phase1_clean_desktop_acceptance.sh manual
  final_beta_phase1_clean_desktop_acceptance.sh help

Modes:

  status
    Reports which Phase 1 records exist.

  inventory
    Scans the current frontend source for raw JSON, developer/test wording,
    fallback wording, inline styles, and button-style surfaces.
    Writes FINAL_BETA_PHASE1_SOURCE_INVENTORY.txt.
    Does not modify runtime source.

  automated
    Runs inventory, the existing tab hit-testing boundary checker, and the
    existing onboarding automated acceptance script.

  manual
    Interactively records the clean-user journey.
    Requires a disposable test profile.
    Does not clear app data automatically.
    Never enter secrets into observations.

  help
    Prints this message.
FINAL_BETA_PHASE1_HELP
}

main() {
  case "$MODE" in
    status)
      run_status
      ;;
    inventory)
      run_inventory
      ;;
    automated)
      run_automated
      ;;
    manual)
      run_manual
      ;;
    help|--help|-h)
      print_help
      ;;
    *)
      printf '%s\n' \
        "FINAL_BETA_PHASE1_ACCEPTANCE=RED" \
        "FAILURE=UNKNOWN_MODE" \
        "MODE=$MODE"

      print_help
      return 1
      ;;
  esac
}

main "$@"
