/**
 * RO:WHAT — Collapsed advanced image use-case and rendition planner for crab://image.
 * RO:WHY — Keeps the default Simple Mint page clean while allowing automatic image version generation.
 * RO:INTERACTS — ImagePage advanced drawer, imageDraftModel, imageRenditionGenerator.js.
 * RO:INVARIANTS — local generated bytes are not truth until upload returns backend crab URLs; no fake CIDs; no hidden spend.
 * RO:METRICS — none.
 * RO:CONFIG — draft useCaseCsv and renditionTargetCsv.
 * RO:SECURITY — no fetching, no execution; generation is local-only until explicit mint flow uploads.
 * RO:TEST — open crab://image → Advanced image options → generate renditions → verify preview list.
 */

import Badge from '../../shared/components/Badge.jsx';
import Button from '../../shared/components/Button.jsx';
import Card from '../../shared/components/Card.jsx';
import {
  DEFAULT_IMAGE_RENDITION_TARGET_CSV,
  IMAGE_RENDITION_TARGET_OPTIONS,
  IMAGE_USE_CASE_OPTIONS,
  csvForRenditionRoles,
  labelFromSnake,
  parseRenditionTargetCsv,
} from './imageDraftModel.js';

export default function ImageRenditions({
  draftState,
  fileFacts,
  localRenditions,
  renditionState,
  onGenerate,
  onClear,
}) {
  const { draft, updateDraft } = draftState;
  const selectedTargets = new Set(parseRenditionTargetCsv(draft.renditionTargetCsv));
  const selectedUseCases = new Set(parseCsv(draft.useCaseCsv || draft.imageRole || 'standalone_image'));
  const entries = Array.isArray(localRenditions?.entries) ? localRenditions.entries : [];
  const status = renditionState?.status || 'idle';

  function toggleTarget(role) {
    const next = new Set(selectedTargets);

    if (next.has(role)) {
      next.delete(role);
    } else {
      next.add(role);
    }

    updateDraft('renditionTargetCsv', csvForRenditionRoles(Array.from(next)));
  }

  function toggleUseCase(value) {
    const next = new Set(selectedUseCases);

    if (next.has(value)) {
      next.delete(value);
    } else {
      next.add(value);
    }

    if (!next.size) {
      next.add('standalone_image');
    }

    updateDraft('useCaseCsv', Array.from(next).join(','));
    updateDraft('imageRole', Array.from(next)[0] || 'standalone_image');
  }

  function selectCommonTargets() {
    updateDraft('renditionTargetCsv', DEFAULT_IMAGE_RENDITION_TARGET_CSV);
  }

  function selectCoverTargets() {
    updateDraft(
      'renditionTargetCsv',
      csvForRenditionRoles(['thumbnail', 'album_cover', 'video_thumbnail', 'film_cover']),
    );
  }

  function selectAllTargets() {
    updateDraft(
      'renditionTargetCsv',
      csvForRenditionRoles(IMAGE_RENDITION_TARGET_OPTIONS.map((target) => target.role)),
    );
  }

  function clearTargets() {
    updateDraft('renditionTargetCsv', '');
    if (typeof onClear === 'function') {
      onClear();
    }
  }

  return (
    <Card
      eyebrow="Advanced"
      title="Image versions"
      className="image-renditions-card image-renditions-card-compact"
      actions={
        <div className="image-simple-card-actions">
          <Badge tone={fileFacts?.name ? 'success' : 'neutral'}>
            {fileFacts?.name ? 'Source selected' : 'No source'}
          </Badge>
          <Badge tone={status === 'ready' ? 'success' : status === 'error' ? 'warning' : 'neutral'}>
            {labelFromSnake(status)}
          </Badge>
          <Badge tone="warning">Local until mint</Badge>
        </div>
      }
    >
      <p className="image-section-copy">
        Select the versions CrabLink should create from the source image. During mint, the source image
        is uploaded first, then each generated version is uploaded as its own .image asset with its own
        backend-returned crab URL.
      </p>

      <section className="image-advanced-mini-section" aria-label="Image use cases">
        <header>
          <strong>Use cases</strong>
          <span>Album cover, video thumbnail, film cover, and similar roles still remain canonical .image assets.</span>
        </header>

        <div className="image-choice-pills">
          {IMAGE_USE_CASE_OPTIONS.map((option) => (
            <button
              key={option.value}
              type="button"
              className={selectedUseCases.has(option.value) ? 'image-choice-pill is-active' : 'image-choice-pill'}
              onClick={() => toggleUseCase(option.value)}
              aria-pressed={selectedUseCases.has(option.value)}
            >
              <span>{option.label}</span>
            </button>
          ))}
        </div>
      </section>

      <section className="image-advanced-mini-section" aria-label="Rendition targets">
        <header>
          <strong>Generated versions</strong>
          <span>These are generated locally, then minted through the backend after explicit ROC confirmation.</span>
        </header>

        <div className="image-rendition-actions">
          <Button variant="secondary" size="sm" onClick={selectCommonTargets}>
            Common web set
          </Button>
          <Button variant="secondary" size="sm" onClick={selectCoverTargets}>
            Covers
          </Button>
          <Button variant="secondary" size="sm" onClick={selectAllTargets}>
            All
          </Button>
          <Button variant="ghost" size="sm" onClick={clearTargets}>
            Clear
          </Button>
          <Button
            variant="primary"
            size="sm"
            onClick={() => onGenerate?.()}
            disabled={!fileFacts?.name || status === 'generating'}
          >
            {status === 'generating' ? 'Generating…' : 'Generate previews'}
          </Button>
        </div>

        <div className="image-choice-pills image-choice-pills-renditions">
          {IMAGE_RENDITION_TARGET_OPTIONS.map((target) => (
            <button
              key={target.role}
              type="button"
              className={selectedTargets.has(target.role) ? 'image-choice-pill is-active' : 'image-choice-pill'}
              onClick={() => toggleTarget(target.role)}
              aria-pressed={selectedTargets.has(target.role)}
              title={`${target.width}×${target.height} · ${target.fit}`}
            >
              <span>{target.label}</span>
              <small>{target.width}×{target.height}</small>
            </button>
          ))}
        </div>
      </section>

      {status === 'error' && (
        <div className="image-rendition-alert" role="alert">
          <strong>Could not generate local previews</strong>
          <span>{renditionState?.error || 'The selected file could not be resized locally.'}</span>
        </div>
      )}

      {status === 'generating' && (
        <div className="image-rendition-alert">
          <strong>Generating versions</strong>
          <span>CrabLink is resizing the selected image locally. No upload is happening yet.</span>
        </div>
      )}

      <section className="image-advanced-mini-section" aria-label="Local generated preview results">
        <header>
          <strong>Generated preview results</strong>
          <span>
            {entries.length
              ? `${entries.length} local versions are ready for the bundle mint flow.`
              : 'No generated previews yet.'}
          </span>
        </header>

        {entries.length ? (
          <div className="image-generated-renditions image-generated-renditions-compact">
            {entries.map((entry) => (
              <article key={entry.role} className="image-generated-rendition">
                <div className="image-generated-rendition-frame">
                  <img src={entry.previewUrl} alt={`${entry.label} local rendition preview`} />
                </div>

                <div className="image-generated-rendition-body">
                  <header>
                    <div>
                      <span>{entry.label}</span>
                      <strong>{entry.width}×{entry.height}</strong>
                    </div>
                    <Badge tone="warning">not minted</Badge>
                  </header>

                  <dl>
                    <div>
                      <dt>Bytes</dt>
                      <dd>{formatBytes(entry.bytes)}</dd>
                    </div>
                    <div>
                      <dt>Type</dt>
                      <dd>{entry.contentType}</dd>
                    </div>
                  </dl>
                </div>
              </article>
            ))}
          </div>
        ) : (
          <p className="image-section-copy">
            Select targets above and click Generate previews. The mint flow will also generate them automatically
            if they are not ready yet.
          </p>
        )}
      </section>
    </Card>
  );
}

function parseCsv(value) {
  return String(value || '')
    .split(',')
    .map((part) => part.trim())
    .filter(Boolean);
}

function formatBytes(value) {
  const bytes = Number(value || 0);

  if (!bytes) return '0 B';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}