#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/CODEBUNDLE_CHROME_EXTENSION.md}"
CHROME_DIR="$ROOT/extensions/chrome"
SHARED_DIR="$ROOT/shared"

if [[ ! -d "$CHROME_DIR" ]]; then
  echo "error: expected Chrome extension folder at: $CHROME_DIR"
  exit 1
fi

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

git_rev="unknown"
git_dirty="unknown"

if command -v git >/dev/null 2>&1 && git -C "$ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git_rev="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"

  if [[ -n "$(git -C "$ROOT" status --porcelain 2>/dev/null)" ]]; then
    git_dirty="dirty"
  else
    git_dirty="clean"
  fi
fi

lang_for_file() {
  case "$1" in
    *.js) echo "javascript" ;;
    *.json) echo "json" ;;
    *.html) echo "html" ;;
    *.css) echo "css" ;;
    *.md) echo "markdown" ;;
    *.sh) echo "bash" ;;
    *.txt) echo "text" ;;
    *) echo "text" ;;
  esac
}

is_binary_file() {
  case "$1" in
    *.png|*.jpg|*.jpeg|*.gif|*.webp|*.ico) return 0 ;;
    *) return 1 ;;
  esac
}

file_size() {
  if stat -f "%z" "$1" >/dev/null 2>&1; then
    stat -f "%z" "$1"
  else
    stat -c "%s" "$1"
  fi
}

hash_file() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  elif command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    echo "sha256-unavailable"
  fi
}

append_file() {
  local abs="$1"
  local rel="${abs#$ROOT/}"
  local lang

  {
    echo
    echo "---"
    echo
    echo "## \`$rel\`"
    echo

    if is_binary_file "$abs"; then
      echo "_Binary file omitted from code block._"
      echo
      echo "- Size bytes: $(file_size "$abs")"
      echo "- SHA-256: $(hash_file "$abs")"
      return
    fi

    lang="$(lang_for_file "$abs")"

    echo "\`\`\`\`$lang"
    cat "$abs"
    echo
    echo "\`\`\`\`"
  } >> "$OUT"
}

{
  echo "<!-- Generated by scripts/make_chrome_codebundle.sh on $timestamp -->"
  echo "# Code Bundle — CrabLink Chrome Extension"
  echo
  echo "> Generated for review/sharing. Source of truth remains the repo."
  echo "> Includes Chrome extension files plus shared browser-client helpers, schemas, fixtures, and relevant scripts."
  echo
  echo "- Root: $ROOT"
  echo "- Generated: $timestamp"
  echo "- Git: $git_rev ($git_dirty)"
  echo
  echo "## Scope"
  echo
  echo '```text'
  echo "extensions/chrome/"
  echo "shared/"
  echo "scripts/check-chrome.sh"
  echo "scripts/package-chrome.sh"
  echo "scripts/smoke-local-gateway.sh"
  echo '```'
  echo
  echo "## File Tree"
  echo
  echo '```text'
} > "$OUT"

if command -v tree >/dev/null 2>&1; then
  (
    cd "$ROOT"
    tree \
      extensions/chrome \
      shared \
      scripts/check-chrome.sh \
      scripts/package-chrome.sh \
      scripts/smoke-local-gateway.sh \
      2>/dev/null || true
  ) >> "$OUT"
else
  (
    cd "$ROOT"
    find \
      extensions/chrome \
      shared \
      scripts/check-chrome.sh \
      scripts/package-chrome.sh \
      scripts/smoke-local-gateway.sh \
      -print 2>/dev/null | sort
  ) >> "$OUT"
fi

{
  echo '```'
  echo
  echo "## Files"
} >> "$OUT"

while IFS= read -r file; do
  append_file "$ROOT/$file"
done < <(
  cd "$ROOT"
  find extensions/chrome shared -type f -print 2>/dev/null | sort
)

for script in \
  scripts/check-chrome.sh \
  scripts/package-chrome.sh \
  scripts/smoke-local-gateway.sh
do
  if [[ -f "$ROOT/$script" ]]; then
    append_file "$ROOT/$script"
  fi
done

echo "wrote: $OUT"