//! RO:WHAT — Binds Native Passport device-key generation to the desktop operating-system CSPRNG.
//! RO:WHY — Physical M1 device identity must originate from unpredictable per-device entropy rather than root derivation, PINs, usernames, or deterministic application state.
//! RO:INTERACTS — svc-passport NativeDeviceKeyRandomSource and getrandom.
//! RO:INVARIANTS — direct OS CSPRNG fill only; no fallback RNG; no persistence and no Passport-vault or platform-factor mutation.
//! RO:METRICS — none; secret-generation material is never labeled.
//! RO:CONFIG — desktop-only Tauri native runtime.
//! RO:SECURITY — generated bytes remain Rust-native; no WebView DTO, serialization, logging, filesystem write, Keychain/DPAPI/Secret-Service write, signing, capability, wallet, or ledger authority.
//! RO:TEST — tests/physical_m1_native_device_os_csprng.rs.

use svc_passport::native::{NativeDeviceKeyGenerationError, NativeDeviceKeyRandomSource};

pub const PHYSICAL_M1_DESKTOP_DEVICE_OS_CSPRNG_LABEL: &str =
    "PHYSICAL_M1_DESKTOP_DEVICE_OS_CSPRNG_V1";

#[derive(Debug, Clone, Copy, Default)]
pub struct OsDesktopNativeDeviceKeyRandomSource;

impl NativeDeviceKeyRandomSource for OsDesktopNativeDeviceKeyRandomSource {
    fn fill(&self, output: &mut [u8]) -> Result<(), NativeDeviceKeyGenerationError> {
        getrandom::fill(output).map_err(|_| NativeDeviceKeyGenerationError::RandomnessUnavailable)
    }
}
